# ===================================================================
#      Smart WebView v8 - Main Configuration File
# ===================================================================

build.application.id=mgks.os.swv
build.version.code=8
build.version.name=8.0.1

build.sdk.compile=36
build.sdk.min=24

debug.mode=false

app.url=https://bbs.886.best/chats
offline.url=file:///android_asset/web/offline.html
search.url=https://bbs.886.best/search
external.url.exception.list=886.best,bbs.886.best

feature.uploads=true
feature.camera.uploads=true
feature.multiple.uploads=true
feature.custom.css=false
feature.copy.paste=true
feature.pull.refresh=false
feature.progress.bar=false
feature.zoom=false
feature.save.form=true
feature.open.external.urls=true
feature.chrome.tabs=true
behavior.back.exits=false
feature.exit.dialog=true

permissions.on.launch=NOTIFICATIONS

security.verify.ssl=true
security.block.screenshots=false
security.accept.thirdparty.cookies=true

ui.orientation=0
ui.layout=0
ui.drawer.header=false
ui.splash.extend=true

agent.postfix.enabled=true
agent.postfix.value=SWVAndroid 886BestApp
agent.override.enabled=false
agent.override.value=Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Mobile Safari/537.36

analytics.gtag.id=

plugins.enabled=RatingPlugin,LocationPlugin,DialogPlugin,JSInterfacePlugin,ToastPlugin,QRScannerPlugin,BiometricPlugin,ImageCompressionPlugin
plugins.playground.enabled=false

rating.install.days=3
rating.launch.times=10
rating.remind.interval=2

biometric.trigger.launch=false
